name: Auto-update versions

on:
  push:
    paths:
      - 'scripts/**/main.js'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update version.txt for changed scripts
        run: |
          for f in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'scripts/.*/main.js'); do
            folder=$(dirname "$f")
            version_file="${folder}/version.txt"
            if [[ -f "$version_file" ]]; then
              current=$(cat "$version_file")
              new=$(printf "%03d" $((10#$current + 1)))
            else
              new="001"
            fi
            echo "$new" > "$version_file"
            echo "Updated $version_file to $new"
          done

      - name: Commit version changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Auto Updater"
          git add scripts/**/version.txt
          git commit -m "Auto-incremented versions" || echo "No version changes"
          git push
